### ISSUE TITLE
Reduzir imagens dentro dos Widgets

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/wp-culturaviva#11]
![captura de tela de 2015-10-03 13 12 05](https://cloud.githubusercontent.com/assets/1244443/10263780/629d8086-69d0-11e5-8d32-2ed10f59aa47.png)

As imagens nos widgets estão sendo baixadas em seu tamanho normal, o que aumenta muito a quantidade de dados baixados.

Existe uma forma de que a imagem seja reduzida pelo servidor proporcionalmente ao tamanho do widget?

**Comment by jacsonp** [comment]
Resolvido por editorial por enquanto
