### ISSUE TITLE
Editar página /saiba-mais

### ISSUE THREAD

**Issue by raissagal** [culturagovbr/wp-culturaviva#16]
- http://culturaviva.gov.br/saiba-mais/
- criar âncoras nos títulos superiores
- inserir botão Entrar para a rede no fim, tal qual no http://culturaviva.gov.br/rede/faq/#autodeclarar
- colocar setinha para subir pro topo
- substituir onde tinha o link http://culturaviva.gov.br/rede/faq/ por http://culturaviva.gov.br/saiba-mais/

**Comment by jacsonp** [comment]
ancoras criadas

**Comment by jacsonp** [comment]
feito tudo menos o link que é com o pessoal do mapasculturais
